add_subdirectory(dynamics/_GeneralModuleFiles)
add_subdirectory(environment/_GeneralModuleFiles)
add_subdirectory(onboardDataHandling/_GeneralModuleFiles)
add_subdirectory(power/_GeneralModuleFiles)

add_subdirectory(deviceInterface/encoder)
add_subdirectory(deviceInterface/hingedBodyLinearProfiler)
add_subdirectory(deviceInterface/motorVoltageInterface)
add_subdirectory(deviceInterface/prescribedLinearTranslation)
add_subdirectory(deviceInterface/prescribedRotation1DOF)
add_subdirectory(deviceInterface/singleAxisProfiler)
add_subdirectory(deviceInterface/tempMeasurement)

add_subdirectory(dynamics/DynOutput/boreAngCalc)
add_subdirectory(dynamics/DynOutput/orbElemConvert)
add_subdirectory(dynamics/ExtPulsedTorque)
add_subdirectory(dynamics/FuelTank)
add_subdirectory(dynamics/GravityGradientEffector)
add_subdirectory(dynamics/HingedRigidBodies)
add_subdirectory(dynamics/Integrators)
add_subdirectory(dynamics/LinearSpringMassDamper)
add_subdirectory(dynamics/MtbEffector)
add_subdirectory(dynamics/NHingedRigidBodies)
add_subdirectory(dynamics/RadiationPressure)
add_subdirectory(dynamics/Thrusters/thrusterDynamicEffector)
add_subdirectory(dynamics/Thrusters/thrusterStateEffector)
add_subdirectory(dynamics/VSCMGs)
add_subdirectory(dynamics/dragEffector)
add_subdirectory(dynamics/dualHingedRigidBodies)
add_subdirectory(dynamics/extForceTorque)
add_subdirectory(dynamics/facetDragEffector)
add_subdirectory(dynamics/facetSRPDynamicEffector)
add_subdirectory(dynamics/gravityEffector)
add_subdirectory(dynamics/hingedRigidBodyMotor)
add_subdirectory(dynamics/linearTranslationalBodies/linearTranslationBodiesOneDOF)
add_subdirectory(dynamics/msmForceTorque)
add_subdirectory(dynamics/prescribedMotion)
add_subdirectory(dynamics/reactionWheels)
add_subdirectory(dynamics/spacecraft)
add_subdirectory(dynamics/sphericalPendulum)
add_subdirectory(dynamics/spinningBodies/spinningBodiesOneDOF)
add_subdirectory(dynamics/spinningBodies/spinningBodiesTwoDOF)
add_subdirectory(dynamics/stateArchitecture)
add_subdirectory(dynamics/stateSpaceEffector)
add_subdirectory(dynamics/stepperMotor)

add_subdirectory(environment/ExponentialAtmosphere)
add_subdirectory(environment/MsisAtmosphere)
add_subdirectory(environment/TabularAtmosphere)
add_subdirectory(environment/albedo)
add_subdirectory(environment/dentonFluxModel)
add_subdirectory(environment/eclipse)
add_subdirectory(environment/ephemerisConverter)
add_subdirectory(environment/groundLocation)
add_subdirectory(environment/groundMapping)
add_subdirectory(environment/magneticFieldCenteredDipole)
add_subdirectory(environment/magneticFieldWMM)
add_subdirectory(environment/planetEphemeris)
add_subdirectory(environment/solarFlux)
add_subdirectory(environment/spacecraftLocation)
add_subdirectory(environment/spiceInterface)

add_subdirectory(navigation/pinholeCamera)
add_subdirectory(navigation/planetHeading)
add_subdirectory(navigation/planetNav)
add_subdirectory(navigation/simpleNav)

add_subdirectory(onboardDataHandling/instrument/mappingInstrument)
add_subdirectory(onboardDataHandling/instrument/simpleInstrument)
add_subdirectory(onboardDataHandling/spaceToGroundTransmitter)
add_subdirectory(onboardDataHandling/storageUnit)
add_subdirectory(onboardDataHandling/transmitter)

add_subdirectory(power/ReactionWheelPower)
add_subdirectory(power/simpleBattery)
add_subdirectory(power/simplePowerMonitor)
add_subdirectory(power/simplePowerSink)
add_subdirectory(power/simpleSolarPanel)

add_subdirectory(sensors/camera)
add_subdirectory(sensors/coarseSunSensor)
add_subdirectory(sensors/hingedRigidBodyMotorSensor)
add_subdirectory(sensors/imuSensor)
add_subdirectory(sensors/magnetometer)
add_subdirectory(sensors/simpleMassProps)
add_subdirectory(sensors/simpleVoltEstimator)
add_subdirectory(sensors/starTracker)

add_subdirectory(simSynch)

add_subdirectory(thermal/motorThermal)
add_subdirectory(thermal/sensorThermal)

add_subdirectory(vizard/cielimInterface)
add_subdirectory(vizard/dataFileToViz)
add_subdirectory(vizard/vizInterface)
