set(module "simulation.dynamics.gravityEffector")
xmera_is_module_enabled("${module}" _is_enabled)
if(_is_enabled)
  xmera_add_swig_module("${module}")
  target_link_libraries("${module}" PRIVATE ArchitectureUtilities dynamicsCommon)
endif()

set(module "simulation.dynamics.gravityModel")
xmera_is_module_enabled("${module}" _is_enabled)
if(_is_enabled)
  xmera_add_swig_module("${module}")
endif()

set(module "simulation.dynamics.pointMassGravityModel")
xmera_is_module_enabled("${module}" _is_enabled)
if(_is_enabled)
  xmera_add_swig_module("${module}")
  target_link_libraries("${module}" PRIVATE ArchitectureUtilities dynamicsCommon)
endif()

set(module "simulation.dynamics.polyhedralGravityModel")
xmera_is_module_enabled("${module}" _is_enabled)
if(_is_enabled)
  xmera_add_swig_module("${module}")
  target_sources("${module}" PRIVATE polyhedralGravityModel.cpp)
endif()

set(module "simulation.dynamics.sphericalHarmonicsGravityModel")
xmera_is_module_enabled("${module}" _is_enabled)
if(_is_enabled)
  xmera_add_swig_module("${module}")
  target_sources("${module}" PRIVATE sphericalHarmonicsGravityModel.cpp)
endif()
