#ifndef MSG_DEFINITIONS_H
#define MSG_DEFINITIONS_H

#define MAX_KEY_POINTS 5000
#define MAX_NUM_CSS_SENSORS 32
#define MAX_EFF_CNT 36
#define RW_EFF_CNT 36

#define MAX_SICP_POINTS 5000
#define SICP_POINT_DIM 3
#define MAX_SICP_ITERATIONS 250

#endif  // MSG_DEFINITIONS_H
