add_subdirectory(_GeneralModuleFiles)
add_subdirectory(attGuidance/_GeneralModuleFiles)
add_subdirectory(transDetermination/_GeneralModuleFiles)

add_subdirectory(attControl/lowPassFilterTorqueCommand)
add_subdirectory(attControl/mrpFeedback)
add_subdirectory(attControl/mrpFeedback_C)
add_subdirectory(attControl/mrpPD)
add_subdirectory(attControl/mrpPD_C)
add_subdirectory(attControl/mrpSteering)
add_subdirectory(attControl/mrpSteering_C)
add_subdirectory(attControl/mtbFeedforward)
add_subdirectory(attControl/mtbMomentumManagement)
add_subdirectory(attControl/mtbMomentumManagementSimple)
add_subdirectory(attControl/prvSteering)
add_subdirectory(attControl/rateControl)
add_subdirectory(attControl/rateDamp)
add_subdirectory(attControl/rateServoFullNonlinear)
add_subdirectory(attControl/rateServoFullNonlinear_C)
add_subdirectory(attControl/thrMomentumManagement)
add_subdirectory(attControl/thrMomentumManagementCpp)

add_subdirectory(attDetermination/CSSEst)
add_subdirectory(attDetermination/InertialUKF)
add_subdirectory(attDetermination/headingSuKF)
add_subdirectory(attDetermination/inertialAttitudeUkf)
add_subdirectory(attDetermination/okeefeEKF)
add_subdirectory(attDetermination/sunlineEKF)
add_subdirectory(attDetermination/sunlineEphem)
add_subdirectory(attDetermination/sunlineSEKF)
add_subdirectory(attDetermination/sunlineSRuKF)
add_subdirectory(attDetermination/sunlineSuKF)
add_subdirectory(attDetermination/sunlineUKF)

add_subdirectory(attGuidance/attRefCorrection)
add_subdirectory(attGuidance/attTrackingError)
add_subdirectory(attGuidance/celestialTwoBodyPoint)
add_subdirectory(attGuidance/celestialTwoBodyPoint_C)
add_subdirectory(attGuidance/constrainedAttitudeManeuver)
add_subdirectory(attGuidance/eulerRotation)
add_subdirectory(attGuidance/flybyPoint)
add_subdirectory(attGuidance/hillPoint)
add_subdirectory(attGuidance/hillPointCpp)
add_subdirectory(attGuidance/inertial3D)
add_subdirectory(attGuidance/inertial3D_C)
add_subdirectory(attGuidance/inertial3DSpin)
add_subdirectory(attGuidance/locationPointing)
add_subdirectory(attGuidance/mrpRotation)
add_subdirectory(attGuidance/mrpRotation_C)
add_subdirectory(attGuidance/oneAxisSolarArrayPoint)
add_subdirectory(attGuidance/opNavPoint)
add_subdirectory(attGuidance/rasterManager)
add_subdirectory(attGuidance/sepPoint)
add_subdirectory(attGuidance/simpleDeadband)
add_subdirectory(attGuidance/sunSafePoint)
add_subdirectory(attGuidance/sunSafePoint_C)
add_subdirectory(attGuidance/sunSearch)
add_subdirectory(attGuidance/sunSearch_C)
add_subdirectory(attGuidance/triad)
add_subdirectory(attGuidance/velocityPoint)
add_subdirectory(attGuidance/waypointReference)

add_subdirectory(dvGuidance/dvAttGuidance)
add_subdirectory(dvGuidance/dvExecuteGuidance)

add_subdirectory(effectorInterfaces/dipoleMapping)
add_subdirectory(effectorInterfaces/errorConversion)
add_subdirectory(effectorInterfaces/forceTorqueThrForceMapping)
add_subdirectory(effectorInterfaces/forceTorqueThrForceMapping_C)
add_subdirectory(effectorInterfaces/hingedRigidBodyPIDMotor)
add_subdirectory(effectorInterfaces/prescribedRot1DOF)
add_subdirectory(effectorInterfaces/prescribedRot2DOF)
add_subdirectory(effectorInterfaces/prescribedTrans)
add_subdirectory(effectorInterfaces/rwMotorTorque)
add_subdirectory(effectorInterfaces/rwMotorTorque_C)
add_subdirectory(effectorInterfaces/rwMotorVoltage)
add_subdirectory(effectorInterfaces/rwMotorVoltage_C)
add_subdirectory(effectorInterfaces/rwNullSpace)
add_subdirectory(effectorInterfaces/rwNullSpace_C)
add_subdirectory(effectorInterfaces/solarArrayReference)
add_subdirectory(effectorInterfaces/stepperMotorController)
add_subdirectory(effectorInterfaces/thrFiringRemainder)
add_subdirectory(effectorInterfaces/thrFiringRemainder_C)
add_subdirectory(effectorInterfaces/thrFiringSchmitt)
add_subdirectory(effectorInterfaces/thrForceMapping)
add_subdirectory(effectorInterfaces/thrMomentumDumping)
add_subdirectory(effectorInterfaces/thrustRWDesat)
add_subdirectory(effectorInterfaces/thrusterPlatformReference)
add_subdirectory(effectorInterfaces/thrusterPlatformState)
add_subdirectory(effectorInterfaces/torque2Dipole)
add_subdirectory(effectorInterfaces/torqueScheduler)

add_subdirectory(formationFlying/etSphericalControl)
add_subdirectory(formationFlying/formationBarycenter)
add_subdirectory(formationFlying/hillStateConverter)
add_subdirectory(formationFlying/hillToAttRef)
add_subdirectory(formationFlying/meanOEFeedback)
add_subdirectory(formationFlying/spacecraftPointing)
add_subdirectory(formationFlying/spacecraftReconfig)

add_subdirectory(imageProcessing/centerOfBrightness)
add_subdirectory(imageProcessing/centerRadiusCNN)
add_subdirectory(imageProcessing/houghCircles)
add_subdirectory(imageProcessing/limbFinding)
add_subdirectory(imageProcessing/opticalFlow)
add_subdirectory(imageProcessing/regionsOfInterest)

add_subdirectory(opticalNavigation/cobConverter)
add_subdirectory(opticalNavigation/faultDetection)
add_subdirectory(opticalNavigation/flybyODuKF)
add_subdirectory(opticalNavigation/horizonOpNav)
add_subdirectory(opticalNavigation/linearODeKF)
add_subdirectory(opticalNavigation/pixelLineBiasUKF)
add_subdirectory(opticalNavigation/pixelLineConverter)
add_subdirectory(opticalNavigation/positionODuKF)
add_subdirectory(opticalNavigation/relativeODuKF)
add_subdirectory(opticalNavigation/timeClosestApproach)
add_subdirectory(opticalNavigation/visualOdometry)

add_subdirectory(orbitControl/lambertPlanner)
add_subdirectory(orbitControl/lambertSecondDV)
add_subdirectory(orbitControl/lambertSolver)
add_subdirectory(orbitControl/lambertSurfaceRelativeVelocity)
add_subdirectory(orbitControl/lambertValidator)
add_subdirectory(orbitControl/smallBodyWaypointFeedback)

add_subdirectory(pointCloudProcessing/SICP)
add_subdirectory(pointCloudProcessing/cameraTriangulation)
add_subdirectory(pointCloudProcessing/initializeICP)
add_subdirectory(pointCloudProcessing/pointCloudTriangulation)

add_subdirectory(rwConfigData)

add_subdirectory(sensorInterfaces/CSSSensorData)
add_subdirectory(sensorInterfaces/IMUSensorData)
add_subdirectory(sensorInterfaces/STSensorData)
add_subdirectory(sensorInterfaces/TAMSensorData)
add_subdirectory(sensorInterfaces/miruLowPassFilterConverter)
add_subdirectory(sensorInterfaces/rateMsgConverter)
add_subdirectory(sensorInterfaces/scanningInstrumentController)
add_subdirectory(sensorInterfaces/simpleInstrumentController)

add_subdirectory(smallBodyNavigation/smallBodyNavEKF)
add_subdirectory(smallBodyNavigation/smallBodyNavUKF)

add_subdirectory(stateEstimation/thrustCMEstimation)

add_subdirectory(transDetermination/chebyPosEphem)
add_subdirectory(transDetermination/dvAccumulation)
add_subdirectory(transDetermination/ephemDifference)
add_subdirectory(transDetermination/ephemDifferenceWithUncertainty)
add_subdirectory(transDetermination/ephemNavConverter)
add_subdirectory(transDetermination/ephemeridesRecenter)
add_subdirectory(transDetermination/navAggregate)
add_subdirectory(transDetermination/oeStateEphem)

add_subdirectory(vehicleConfigData)
