add_library(messaging INTERFACE)
add_library(Xmera::Messaging ALIAS messaging)

target_sources(messaging
  PUBLIC FILE_SET HEADERS
  BASE_DIRS "${CMAKE_SOURCE_DIR}"
  FILES
    messaging.h
    msgHeader.h
    ../msgPayloadDef/definitions.h
    # ... and more added later via `xmera_add_swig_message`
)

target_link_libraries(messaging INTERFACE
  Xmera::Core
)

install(TARGETS messaging
  EXPORT xmera
  DESTINATION lib
  FILE_SET HEADERS
    DESTINATION include
)

install(PROGRAMS "msgAutoSource/generateSWIGModules.py"
  DESTINATION bin
)

install(FILES "msgAutoSource/msgInterfacePy.i.in"
  DESTINATION usr/share/xmera
)

install(FILES "newMessaging.ih"
  DESTINATION include/architecture/messaging)

xmera_add_swig_message(messaging AccDataMsgPayload)
xmera_add_swig_message(messaging AccPktDataMsgPayload)
xmera_add_swig_message(messaging AccessMsgPayload)
xmera_add_swig_message(messaging AlbedoMsgPayload)
xmera_add_swig_message(messaging ArrayEffectorLockMsgPayload)
xmera_add_swig_message(messaging ArrayMotorForceMsgPayload)
xmera_add_swig_message(messaging ArrayMotorTorqueMsgPayload)
xmera_add_swig_message(messaging AtmoPropsMsgPayload)
xmera_add_swig_message(messaging AttGuidMsgPayload)
xmera_add_swig_message(messaging AttRefMsgPayload)
xmera_add_swig_message(messaging AttStateMsgPayload)
xmera_add_swig_message(messaging BodyHeadingMsgPayload)
xmera_add_swig_message(messaging BoreAngleMsgPayload)
xmera_add_swig_message(messaging CMEstDataMsgPayload)
xmera_add_swig_message(messaging CSSArraySensorMsgPayload)
xmera_add_swig_message(messaging CSSConfigLogMsgPayload)
xmera_add_swig_message(messaging CSSConfigMsgPayload)
xmera_add_swig_message(messaging CSSRawDataMsgPayload)
xmera_add_swig_message(messaging CSSUnitConfigMsgPayload)
xmera_add_swig_message(messaging CameraConfigMsgPayload)
xmera_add_swig_message(messaging CameraImageMsgPayload)
xmera_add_swig_message(messaging CameraLocalizationMsgPayload)
xmera_add_swig_message(messaging CameraModelMsgPayload)
xmera_add_swig_message(messaging CameraRenderingMsgPayload)
xmera_add_swig_message(messaging CelestialBodyParametersMsgPayload)
xmera_add_swig_message(messaging ChargeMsmMsgPayload)
xmera_add_swig_message(messaging ClassicElementsMsgPayload)
xmera_add_swig_message(messaging CmdForceBodyMsgPayload)
xmera_add_swig_message(messaging CmdForceInertialMsgPayload)
xmera_add_swig_message(messaging CmdTorqueBodyMsgPayload)
xmera_add_swig_message(messaging ColorMsgPayload)
xmera_add_swig_message(messaging DataNodeUsageMsgPayload)
xmera_add_swig_message(messaging DataStorageStatusMsgPayload)
xmera_add_swig_message(messaging DesiredVelocityMsgPayload)
xmera_add_swig_message(messaging DeviceCmdMsgPayload)
xmera_add_swig_message(messaging DeviceStatusMsgPayload)
xmera_add_swig_message(messaging DipoleRequestBodyMsgPayload)
xmera_add_swig_message(messaging DirectionOfMotionMsgPayload)
xmera_add_swig_message(messaging DvBurnCmdMsgPayload)
xmera_add_swig_message(messaging DvExecutionDataMsgPayload)
xmera_add_swig_message(messaging EclipseMsgPayload)
xmera_add_swig_message(messaging EphemerisMsgPayload)
xmera_add_swig_message(messaging EpochMsgPayload)
xmera_add_swig_message(messaging FilterMsgPayload)
xmera_add_swig_message(messaging FilterResidualsMsgPayload)
xmera_add_swig_message(messaging FuelTankMsgPayload)
xmera_add_swig_message(messaging GravityGradientMsgPayload)
xmera_add_swig_message(messaging GroundStateMsgPayload)
xmera_add_swig_message(messaging HeadingFilterMsgPayload)
xmera_add_swig_message(messaging HillRelStateMsgPayload)
xmera_add_swig_message(messaging HingedRigidBodyMsgPayload)
xmera_add_swig_message(messaging IMUSensorBodyMsgPayload)
xmera_add_swig_message(messaging IMUSensorMsgPayload)
xmera_add_swig_message(messaging InertialFilterMsgPayload)
xmera_add_swig_message(messaging InertialHeadingMsgPayload)
xmera_add_swig_message(messaging LambertPerformanceMsgPayload)
xmera_add_swig_message(messaging LambertProblemMsgPayload)
xmera_add_swig_message(messaging LambertSolutionMsgPayload)
xmera_add_swig_message(messaging LambertValidatorMsgPayload)
xmera_add_swig_message(messaging LandmarkMsgPayload)
xmera_add_swig_message(messaging LinearTranslationRigidBodyMsgPayload)
xmera_add_swig_message(messaging MTBArrayConfigMsgPayload)
xmera_add_swig_message(messaging MTBCmdMsgPayload)
xmera_add_swig_message(messaging MTBMsgPayload)
xmera_add_swig_message(messaging MagneticFieldMsgPayload)
xmera_add_swig_message(messaging ModuleTemplateMsgPayload)
xmera_add_swig_message(messaging MotorStepCommandMsgPayload)
xmera_add_swig_message(messaging NavAttMsgPayload)
xmera_add_swig_message(messaging NavTransMsgPayload)
xmera_add_swig_message(messaging OpNavCOBMsgPayload)
xmera_add_swig_message(messaging OpNavCOMMsgPayload)
xmera_add_swig_message(messaging OpNavCirclesMsgPayload)
xmera_add_swig_message(messaging OpNavFilterMsgPayload)
xmera_add_swig_message(messaging OpNavLimbMsgPayload)
xmera_add_swig_message(messaging OpNavMsgPayload)
xmera_add_swig_message(messaging OpNavUnitVecMsgPayload)
xmera_add_swig_message(messaging PairedKeyPointsMsgPayload)
xmera_add_swig_message(messaging PixelLineFilterMsgPayload)
xmera_add_swig_message(messaging PlasmaFluxMsgPayload)
xmera_add_swig_message(messaging PointCloudMsgPayload)
xmera_add_swig_message(messaging PowerNodeStatusMsgPayload)
xmera_add_swig_message(messaging PowerNodeUsageMsgPayload)
xmera_add_swig_message(messaging PowerStorageStatusMsgPayload)
xmera_add_swig_message(messaging PrescribedMotionMsgPayload)
xmera_add_swig_message(messaging PrescribedRotationMsgPayload)
xmera_add_swig_message(messaging PrescribedTranslationMsgPayload)
xmera_add_swig_message(messaging PyBatteryMsgPayload)
xmera_add_swig_message(messaging RWArrayConfigMsgPayload)
xmera_add_swig_message(messaging RWAvailabilityMsgPayload)
xmera_add_swig_message(messaging RWCmdMsgPayload)
xmera_add_swig_message(messaging RWConfigElementMsgPayload)
xmera_add_swig_message(messaging RWConfigLogMsgPayload)
xmera_add_swig_message(messaging RWConfigMsgPayload)
xmera_add_swig_message(messaging RWConstellationMsgPayload)
xmera_add_swig_message(messaging RwMotorTorqueMsgPayload)
xmera_add_swig_message(messaging RwMotorVoltageMsgPayload)
xmera_add_swig_message(messaging RWSpeedMsgPayload)
xmera_add_swig_message(messaging RateCmdMsgPayload)
xmera_add_swig_message(messaging RealTimeFactorMsgPayload)
xmera_add_swig_message(messaging ReconfigBurnArrayInfoMsgPayload)
xmera_add_swig_message(messaging ReconfigBurnInfoMsgPayload)
xmera_add_swig_message(messaging SCEnergyMomentumMsgPayload)
xmera_add_swig_message(messaging SCMassPropsMsgPayload)
xmera_add_swig_message(messaging SCStatesMsgPayload)
xmera_add_swig_message(messaging SICPMsgPayload)
xmera_add_swig_message(messaging STAttMsgPayload)
xmera_add_swig_message(messaging STSensorMsgPayload)
xmera_add_swig_message(messaging SmallBodyNavMsgPayload)
xmera_add_swig_message(messaging SmallBodyNavUKFMsgPayload)
xmera_add_swig_message(messaging SolarFluxMsgPayload)
xmera_add_swig_message(messaging SpicePlanetStateMsgPayload)
xmera_add_swig_message(messaging SpiceTimeMsgPayload)
xmera_add_swig_message(messaging StepperMotorMsgPayload)
xmera_add_swig_message(messaging SunlineFilterMsgPayload)
xmera_add_swig_message(messaging SwDataMsgPayload)
xmera_add_swig_message(messaging SynchClockMsgPayload)
xmera_add_swig_message(messaging TAMSensorBodyMsgPayload)
xmera_add_swig_message(messaging TAMSensorMsgPayload)
xmera_add_swig_message(messaging TDBVehicleClockCorrelationMsgPayload)
xmera_add_swig_message(messaging THRArrayCmdForceMsgPayload)
xmera_add_swig_message(messaging THRArrayConfigMsgPayload)
xmera_add_swig_message(messaging THRArrayOnTimeCmdMsgPayload)
xmera_add_swig_message(messaging THRConfigMsgPayload)
xmera_add_swig_message(messaging THROutputMsgPayload)
xmera_add_swig_message(messaging TemperatureMsgPayload)
xmera_add_swig_message(messaging TimeClosestApproachMsgPayload)
xmera_add_swig_message(messaging TransRefMsgPayload)
xmera_add_swig_message(messaging VSCMGArrayTorqueMsgPayload)
xmera_add_swig_message(messaging VSCMGCmdMsgPayload)
xmera_add_swig_message(messaging VSCMGConfigMsgPayload)
xmera_add_swig_message(messaging VSCMGSpeedMsgPayload)
xmera_add_swig_message(messaging VehicleConfigMsgPayload)
xmera_add_swig_message(messaging VoltMsgPayload)
